# Generated by Django 4.1.2 on 2022-11-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('email_id', models.CharField(max_length=500)),
                ('phn_no', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=500)),
                ('phn_no', models.CharField(max_length=500)),
                ('eid', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=750)),
                ('dateb', models.DateField(unique=True)),
                ('vname', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='community_hall',
            fields=[
                ('community_hall_id', models.AutoField(primary_key=True, serialize=False)),
                ('community_hall_name', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('locality', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1500)),
                ('contact_no', models.CharField(max_length=500)),
                ('capacity', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('manager_name', models.CharField(max_length=500)),
                ('community_hall_email_id', models.CharField(max_length=500)),
                ('cost', models.PositiveIntegerField()),
                ('img', models.ImageField(upload_to='Photos')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('email_id', models.CharField(max_length=500)),
                ('phn_no', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='garden',
            fields=[
                ('garden_id', models.AutoField(primary_key=True, serialize=False)),
                ('garden_name', models.CharField(max_length=1500)),
                ('city', models.CharField(max_length=500)),
                ('locality', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1500)),
                ('contact_no', models.CharField(max_length=500)),
                ('capacity', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('manager_name', models.CharField(max_length=500)),
                ('garden_email_id', models.CharField(max_length=500)),
                ('cost', models.PositiveIntegerField()),
                ('img', models.ImageField(upload_to='Photos')),
            ],
        ),
        migrations.CreateModel(
            name='hall',
            fields=[
                ('hall_id', models.AutoField(primary_key=True, serialize=False)),
                ('hall_name', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('locality', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1500)),
                ('contact_no', models.CharField(max_length=500)),
                ('capacity', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('manager_name', models.CharField(max_length=500)),
                ('hall_email_id', models.CharField(max_length=500)),
                ('cost', models.PositiveIntegerField()),
                ('img', models.ImageField(upload_to='Photos')),
            ],
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('email_id', models.CharField(max_length=500)),
                ('phn_no', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='pool',
            fields=[
                ('pool_id', models.AutoField(primary_key=True, serialize=False)),
                ('pool_name', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('locality', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1500)),
                ('contact_no', models.CharField(max_length=500)),
                ('capacity', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('manager_name', models.CharField(max_length=500)),
                ('pool_email_id', models.CharField(max_length=500)),
                ('cost', models.PositiveIntegerField()),
                ('img', models.ImageField(upload_to='Photos')),
            ],
        ),
    ]
