# Generated by Django 4.1.2 on 2022-11-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookable1', '0002_booked_community_hall_booked_garden_booked_pool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked_community_hall',
            name='dateb',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booked_garden',
            name='dateb',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booked_hall',
            name='dateb',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booked_pool',
            name='dateb',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booked_venues',
            name='dateb',
            field=models.DateField(),
        ),
    ]
