# Generated by Django 4.1.2 on 2022-11-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookable1', '0003_alter_booked_community_hall_dateb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='booked_community_halls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=500)),
                ('phn_no', models.CharField(max_length=500)),
                ('eid', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=750)),
                ('vname', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='booked_gardens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=500)),
                ('phn_no', models.CharField(max_length=500)),
                ('eid', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=750)),
                ('vname', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='booked_pools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=500)),
                ('phn_no', models.CharField(max_length=500)),
                ('eid', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=750)),
                ('vname', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='booked_venues',
            new_name='booked_halls',
        ),
        migrations.RenameModel(
            old_name='booked_community_hall',
            new_name='requested_community_hall',
        ),
        migrations.RenameModel(
            old_name='booked_garden',
            new_name='requested_garden',
        ),
        migrations.RenameModel(
            old_name='booked_hall',
            new_name='requested_hall',
        ),
        migrations.RenameModel(
            old_name='booked_pool',
            new_name='requested_pool',
        ),
    ]
