# Generated by Django 4.1.2 on 2022-11-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookable1', '0004_booked_community_halls_booked_gardens_booked_pools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked_community_halls',
            name='type',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='booked_gardens',
            name='type',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='booked_halls',
            name='type',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='booked_pools',
            name='type',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='requested_community_hall',
            name='type',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='requested_garden',
            name='type',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='requested_hall',
            name='type',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='requested_pool',
            name='type',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
