# Generated by Django 4.1.3 on 2022-11-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookable1', '0006_remove_booked_community_halls_dateb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requested_hall',
            name='dateend',
            field=models.DateTimeField(default=None),
        ),
    ]
